WIKIHOW_SYSTEM_PROMPT = '''In this task, you will evaluate the quality of the methods generated by the response. The evaluation should focus on each method’s clarity, practical utility, and effectiveness in achieving the intended goal. This evaluation task focuses on five key criteria that assess different aspects of the method, along with one optional criterion for penalizing harmful content. Note that the emotional aspect will not add to the score, but if the response contains harmful intentions or negative impacts, the score should be decreased by 1 point.
Here are the detailed criteria of each aspect: 
1) Text Quality: The method should be written in clear, understandable language, free from grammatical errors, and structured logically, making it easy to follow and implement. 
2) Image Quality: The image descriptions should be vivid and relevant, enhancing the comprehension of the method by allowing the reader to visualize the steps. The text should still be self-sufficient without the images. 
3) Text-Image Coherence: The images and text should work together seamlessly, with each image description corresponding logically to specific steps in the text, enhancing the overall understanding of the method. 
4) Method Quality and Practical Utility: The method should be actionable, clearly explaining each step in sufficient detail to ensure the user can follow and apply it successfully in real-world scenarios. Depth and thoroughness of the explanation are more important than variety. 
5) Creativity and Engagement: The method should offer a unique or creative approach, making the instructional process engaging while ensuring the method remains clear and effective. 
6) Emotional Impact (penalty only): This criterion will only be used to deduct points. If the response contains harmful, negative, or inappropriate emotions (such as violence or aggressive language), deduct 1 point. Otherwise, no score change will be made. 
I will give you the question and answer pair. You should give your feedback about the quality of the answer, beginning with '### Feedback\n'. After giving the feedback, use the above criteria to give the final score, beginning with '### Score\n'.'''

VIST_SYSTEM_PROMPT = '''This evaluation task focuses on six key criteria that assess different aspects of visual storytelling. Note that the emotional aspect will not add to the score but can decrease the score by 1 point if the response contains negative emotions or other harmful impacts. Here are the detailed criteria of each aspect: 
1) Text Quality: Evaluate the clarity, grammatical accuracy, and engagement of the text. The narrative should be easy to understand, free from errors, and presented in a way that captures the reader's interest. Descriptions and dialogue should be well-crafted, supporting the overall flow of the story. 
2) Image Quality: Assess the quality of the image descriptions. Although no actual images are present, the descriptions should be vivid, detailed, and clear enough to allow the reader to visualize the scene. Effective image descriptions should enhance the storytelling experience without being overly complex. 
3) Text-Image Coherence: Determine how well the text and image descriptions complement each other. The integration should be seamless, with the visual descriptions enhancing and supporting the narrative. Both elements should work together to create a unified and immersive experience. 
4) Context Consistency: Evaluate the overall consistency of the story's setting, characters, and plot. The narrative should maintain a logical and coherent flow, with no contradictions or inconsistencies in its context or progression. This also includes temporal and spatial transitions, ensuring that the story remains believable and cohesive. 
5) Innovation: Assess the creativity and originality of the content. Look for fresh ideas, unique plotlines, and innovative storytelling techniques. The narrative should avoid clichés and predictable story arcs, using creative visual descriptions to add depth and interest. 
6) Emotional Impact: This is not a scoring criterion unless the story includes negative emotions. If the response conveys harmful or inappropriate emotions, deduct 1 point. Otherwise, no score change will be made.
I will give you the question and answer pair. You should give your feedback about the quality of the answer, beginning with '### Feedback\n'. After giving the feedback, use the above criteria to give the final score, beginning with '### Score\n'.'''

MATH_PROMPT = '''In this task, you will evaluate the quality of the model's response to a math question. The evaluation will focus on five key aspects: 
1) **Question Text Understanding**: Assess whether the model correctly understands and interprets the textual information given in the question, identifying key mathematical elements, relationships, or instructions from the text. 
2) **Question Image Understanding**: Evaluate the model’s understanding of the visual information (if applicable) in the question, including any diagrams, charts, or figures. The model should correctly interpret the visual elements and integrate them into the solution. 
3) **Reasoning Clarity**: The model should provide a clear, step-by-step explanation of its reasoning process, logically connecting the problem's details to the steps leading toward a solution. This should be easy to follow and free from unnecessary complexity. 
4) **Partial Correctness in Reasoning**: Even if the final answer is incorrect, evaluate whether the model shows correct intermediate steps, partial reasoning, or progress toward the right solution. This includes identifying whether the model has applied appropriate mathematical principles or formulas in parts of the response. 
5) **Final Answer Accuracy**: Determine whether the model arrives at the correct final answer, based on both the problem statement and the reasoning provided. An accurate answer, supported by correct reasoning, should receive the highest score.
I will give you the question and answer pair. You should give your feedback about the quality of the answer, beginning with '### Feedback\n'. After giving the feedback, use the above criteria to give the final score, beginning with '### Score\n'.'''

def get_ask_prompt(dataset):
    if dataset == "wikihow":
        return "### Question\n{question}\nWhat should I do next? Explain it to me with text and images.\n"
    elif dataset == "vist":
        return "Episode 1:{question}\nContinue the story by writing brief paragraphs and generate an image to each paragraph.\n"
    else:
        return "### Question\n{question}\n"

def get_ask_prompt2(dataset):
    if dataset == "wikihow":
        return "What should I do next? Explain it to me with text and images.\n"
    elif dataset == "vist":
        return "Continue the story by writing brief paragraphs and generate an image to each paragraph.\n"
    else:
        return ""

def get_prompt(dataset):
    if "wikihow" in dataset:
        return WIKIHOW_SYSTEM_PROMPT + "### Question\n{question}\n### Answer\n{answer}\n### Feedback\n"
    elif "vist" in dataset:
        return VIST_SYSTEM_PROMPT + "### Question\n{question}\n### Answer\n{answer}\n### Feedback\n"
    elif 'remi' in dataset:
        return MATH_PROMPT + "### Question\n{question}\n### Answer\n{answer}\n### Feedback\n"
    elif 'mathvista' in dataset:
        return MATH_PROMPT + "### Question\n{question}\n### Answer\n{answer}\n### Correct Answer\nThe correct answer to this question should be: {gt_answer}\n### Feedback\n"

def get_training_prompt(dataset):
    if "wikihow" in dataset:
        return WIKIHOW_SYSTEM_PROMPT + "### Question\n{question}\n### Answer\n{answer}\n", "### Feedback\n{feedback}\n\n### Score\n{score}\n"
    elif "vist" in dataset:
        return VIST_SYSTEM_PROMPT + "### Question\n{question}\n### Answer\n{answer}\n", "### Feedback\n{feedback}\n\n### Score\n{score}\n"
    elif 'remi' in dataset:
        return MATH_PROMPT + "### Question\n{question}\n### Answer\n{answer}\n### Feedback\n"
    elif 'mathvista' in dataset:
        return MATH_PROMPT + "### Question\n{question}\n### Answer\n{answer}\n", "### Feedback\n{feedback}\n\n### Score\n{score}\n"